MDScreen:
    name: 'develop'
    FitImage:
        source: 'assets/bg.jpg'
    Image:
        source: 'assets/pngegg.png'
        size_hint: .5,.5
        pos_hint: {'center_x':0.5,'center_y':0.7}
    MDLabel:
        text:'This feature is under development'
        font_name: 'assets/Poppins-Medium'
        font_size: '25sp'
        pos_hint: {'center_x':0.5,'center_y':0.4}
        halign: 'center'